src/Entity/Products.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use App\Entity\Trait\SlugTrait;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Trait\CreatedAtTrait;
use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: ProductsRepository::class)]
class Products
{

    use CreatedAtTrait;
    use SlugTrait;
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $categories = null;

    #[ORM\OneToMany(mappedBy: 'products', targetEntity: Images::class, orphanRemoval: true)]
    private Collection $images;

    #[ORM\OneToMany(mappedBy: 'products', targetEntity: OrdersDetails::class)]
    private Collection $ordersDetails;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img_name = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->ordersDetails = new ArrayCollection();
        $this->created_at = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getCategories(): ?Categories
    {
        return $this->categories;
    }

    public function setCategories(?Categories $categories): static
    {
        $this->categories = $categories;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setProducts($this);
        }

        return $this;
    }

    public function removeImage(Images $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProducts() === $this) {
                $image->setProducts(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, OrdersDetails>
     */
    public function getOrdersDetails(): Collection
    {
        return $this->ordersDetails;
    }

    public function addOrdersDetail(OrdersDetails $ordersDetail): static
    {
        if (!$this->ordersDetails->contains($ordersDetail)) {
            $this->ordersDetails->add($ordersDetail);
            $ordersDetail->setProducts($this);
        }

        return $this;
    }

    public function removeOrdersDetail(OrdersDetails $ordersDetail): static
    {
        if ($this->ordersDetails->removeElement($ordersDetail)) {
            // set the owning side to null (unless already changed)
            if ($ordersDetail->getProducts() === $this) {
                $ordersDetail->setProducts(null);
            }
        }

        return $this;
    }

    public function getImgName(): ?string
    {
        return $this->img_name;
    }

    public function setImgName(?string $img_name): static
    {
        $this->img_name = $img_name;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Products;
use App\Repository\CouponsRepository;
use App\Repository\ProductsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;



    #[Route('/cart', name: 'cart_')]
    class CartController extends AbstractController
    {

    #[Route('/', name: 'index')]
    public function index(SessionInterface $session, ProductsRepository $productsRespository, Request $request, CouponsRepository $couponsRepository)
    {
        $panier = $session->get('panier', []);
        // Initialisation
        $data = [];
        $total = 0;
    
        foreach($panier as $id => $quantity) {
            $product = $productsRespository->find($id);
            
            // Vérifie si le produit existe
            if ($product) {
                $data[] = [
                    'product' => $product,
                    'quantity' => $quantity,
                ];
                $total += $product->getPrice() * $quantity;
            }
        }
    
        $totalItems = $this->calculateTotalItems($panier);
    
        // Récupération du coupon de la session
        $discount = $session->get('discount', 0);
    
        $couponCode = $request->request->get('code');
    
        // Si un nouveau coupon est envoyé
        if ($couponCode) {
            $coupon = $couponsRepository->findOneBy(['code' => $couponCode]);
            if ($coupon && $coupon->isIsValid()) {
                $discount = $coupon->getDiscount();
                // Save de la discount en session
                $session->set('discount', $discount);
            }
        }
    
        // Application de la remise
        $total = $total - ($total * $discount / 100); 
    
        return $this->render("cart/index.html.twig", [
            'data' => $data,
            'total' => $total,
            'totalItems' => $totalItems,
            'discount' => $discount 
        ]);
    }
    


    private function calculateTotalItems($cart)
    {
        $totalItems = 0;
        foreach ($cart as $quantity) {  
            $totalItems += $quantity;
        }
        return $totalItems;
    }
    

    #[Route('/add/{id}', name: 'add')]
    public function add(Products $product, SessionInterface $session, EntityManagerInterface $em, Request $request, ProductsRepository  $productsRepository)
    {
        $id = $product->getId();
        $panier = $session->get('panier', []);
      
    
        if($product->getStock() > 0) {
            if(!isset($panier[$id])) {
                $panier[$id] = 0;
            }
            $panier[$id]++;
        
            // Décrémente le stock du produit
            $product->setStock($product->getStock() - 1);
            $em->persist($product);  
            $em->flush();
        
            // Met à jour le panier dans la session
            $session->set('panier', $panier);
        } else {
            $this->addFlash('warning', 'Le produit ' . $product->getName() . ' est en rupture de stock.');
        }
    
        $total = 0;
        foreach($panier as $id => $quantity){
            $product = $productsRepository->find($id);
            $total += $product->getPrice() * $quantity;
        }
    
        $totalItems = $this->calculateTotalItems($session->get('panier', []));
    
        // Si la requête est en AJAX, retourne une réponse JSON
        if ($request->isXmlHttpRequest()) {
            return new JsonResponse([
                'totalItems' => $totalItems,
                'total' => $total,
                'productId' => $id, 
                'newStock' => $product->getStock(),
                'newQuantity' => $panier[$id]  
            ]);
        }
        
        return $this->redirectToRoute('cart_index');
    }
    

    #[Route('/remove/{id}', name: 'remove')]
    public function remove(Products $product, SessionInterface $session, EntityManagerInterface $em, Request $request)
    {
        $id = $product->getId();

        $panier = $session->get('panier', []);

        if(!empty($panier[$id])){
            if($panier[$id] > 1) {
                $panier[$id] -- ;
            }else {
                unset($panier[$id]);
            }

            //Incrémente la quantité du produit en DB avec em
            $product->setStock($product->getStock() + 1);
            $em->flush();

        $session->set('panier', $panier);

        $totalItems = $this->calculateTotalItems($session->get('cart', []));

        // Si la requête est en AJAX, retourne une réponse JSON
        if ($request->isXmlHttpRequest()) {
            return new JsonResponse(['totalItems' => $totalItems]);
        }
    
        return $this->redirectToRoute('cart_index');

        }
    }

    #[Route('/delete/{id}', name: 'delete')]
    public function delete(Products $product, SessionInterface $session, Request $request)
    {
        $id = $product->getId();

        $panier = $session->get('panier', []);

        if(!empty($panier[$id])){
                unset($panier[$id]);
            }

        $session->set('panier', $panier);

        $totalItems = $this->calculateTotalItems($session->get('panier', []));

        // Si la requête est en AJAX, retournez une réponse JSON
        if ($request->isXmlHttpRequest()) {
        return new JsonResponse(['totalItems' => $totalItems]);
    }
    
        return $this->redirectToRoute('cart_index');
        
    }

    #[Route('/vider', name: 'vider')]
    public function vider(SessionInterface $session, Request $request)
    {
    
        $session->remove('panier');

        $totalItems = 0;  

        // Si la requête est en AJAX, retournez une réponse JSON
        if ($request->isXmlHttpRequest()) {
        return new JsonResponse(['totalItems' => $totalItems]);
    }
    
        return $this->redirectToRoute('cart_index');
        
    }


#[Route("/add-to-cart", name: "add_to_cart", methods:["POST"])]
public function addToCart(Request $request, SessionInterface $session, ProductsRepository $productsRepository)
{
    $productId = $request->request->get('productId');

    // Validation du produit
    if (!is_numeric($productId) || $productId <= 0) {
        return new JsonResponse([
            'message' => 'Produit invalide.',
        ], JsonResponse::HTTP_BAD_REQUEST);
    }

    try {
        $cart = $session->get('panier', []);

        // Recherche du produit dans la base de données
        $product = $productsRepository->find($productId);
        if (!$product) {
            return new JsonResponse([
                'message' => 'Produit non trouvé.',
            ], JsonResponse::HTTP_NOT_FOUND);
        }

        // Ajout du produit au panier
        if (!isset($cart[$productId])) {
            $cart[$productId] = 0;
        }
        $cart[$productId]++;

        $session->set('panier', $cart);
        // Réponse avec le nombre d'articles dans le panier et un message
        return new JsonResponse([
            'message' => 'Le produit a été ajouté au panier.',
            'cartCount' => array_sum($cart) // Total des produits dans le panier
        ]);
    } catch (\Exception $e) {
        // Gestion des exceptions
        return new JsonResponse([
            'message' => 'Une erreur est survenue lors de l\'ajout du produit au panier.',
        ], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
    }
}


#[Route('/update-cart', name: 'update_cart', methods: ["POST"])]
public function updateCart(SessionInterface $session, Request $request, ProductsRepository $productsRepository, CouponsRepository $couponsRepository)
{
    // Récupérer les données de la requête
    $productId = $request->request->get('productId');
    $quantity = $request->request->get('quantity');
    
    // Mettre à jour la quantité dans la session
    $panier = $session->get('panier', []);
    $panier[$productId] = $quantity;
    $session->set('panier', $panier);
    
    // Initialisation
    $data = [];
    $total = 0;
    $totalItems = 0;

    // Calcul du total
    foreach($panier as $id => $quantity){
        $product = $productsRepository->find($id);
        if ($product) {
            $total += $product->getPrice() * $quantity;
            $totalItems += $quantity;
        }
    }

    // Récupération du coupon de la session
    $discount = $session->get('discount', 0);

    // Application de la remise
    $total = $total - ($total * $discount / 100);
    
    return new JsonResponse([
        'total' => $total,
        'totalItems' => $totalItems,
        'discount' => $discount
    ]);
}

}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier de {{ app.user.firstname }}{% endblock %}

{% block body %}

<div class="full-background">
    <div class="content-wrapper">
        <div class="left-block">

    <main class="container">
    {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endfor %}
        <section class="row">

            <div class="col-12">
                <h1 class="main-title margin-title-cart">Panier de {{ app.user.firstname }} </h1>
                
            </div>

                <div class="card mb-5 card-color">

                        <div class="cards-container">
                            {% for element in data %}
                            <div class="card card-shadow card-background">
                                <img src="{{ asset('img/' ~ element.product.imgName) }}" alt="{{ element.product.name }}" class="card-image testt">
                                <div class="card-body2">
                                    <h2 class="card-title">{{ element.product.name }}</h2>
                                    <p class="card-price">{{ element.product.price / 100 }} €</p>
                                    <p class="card-quantity">
                                        Quantité : {{ element.quantity }} &nbsp;
                                        <a href="{{ path("cart_add", { id: element.product.id }) }}" class="btn btn-success">+</a>
                                        <a href="{{ path("cart_remove", { id: element.product.id }) }}" class="btn btn-warning">-</a>
                                       
                                    </p>
                                    <p class="card-subtotal"> En stock : <span id="stockForProduct{{ element.product.id }}">{{ element.product.stock }}</span></p>
                                    <p class="card-subtotal">{{ element.quantity * element.product.price / 100 }} €</p>
                                    <a href="{{ path("cart_delete", { id: element.product.id }) }}" class="btn btn-danger">Supprimer</a>
                                </div>
                                </div>
                            {% else %}
                                <p>Votre panier est vide.</p>
                            {% endfor %}
                        </div>  

                </div>

        </section>
 
    </main>   
    </div>

        <div class="right-block">
            <div class="card summary-card">
                <div class="card-body">
                    <h2 class="card-title vold">Récapitulatif :</h2>
                    <p class="card-info" id="totalItems">Total : <span class="gold ">{{ totalItems is defined ? totalItems : 0 }}</span> article(s)</p>
                    <p class="card-info letter-spa">
                  Prix total : <span id="total" class="gold">{{ (total / 100)|number_format(2, '.', '') }} €</span>
                    <span id="discount" class="text-success">
                        {% if discount > 0 %} 
                        ({{ discount }}% de remise)
                        {% endif %}
                    </span>
                    </p>


                    
                    <button class="btn btn-danger2">
                        <a href="{{ path("cart_vider") }}" class="">Vider</a>
                    </button>
                    
                </div>
            </div>

            <div class="card summary-card">
                <div class="card-body">                  
                    <form action="{{ path('cart_index') }}" method="post">
                        <div class="coupon-code">
                            <input type="text" name="code" class="input-code" placeholder="Code promo" />
                            <button type="submit" class="btn btn-success btn-success2">Valider</button>
                        </div>
                    </form>
                    
                </div>
            </div>

        </div>
    </div>
</div>


{% endblock %}